language: rust
rust:
  - nightly
addons:
    apt:
        packages:
            - libssl-dev

cache: cargo

before_script:
 - cargo install cargo-tarpaulin
 - set -e

script:
 - cargo clean
 - cargo build
 - cargo test
 - cargo test --package relp --all-features --release --test mod
 - cargo build --bin relp --features="binaries"

after_success:
 - cargo tarpaulin --ignore-tests --out Xml
 - bash <(curl -s https://codecov.io/bash) 

