[package]
name = "rust-lp"
version = "0.0.4"
authors = ["Bram van den Heuvel <bram@vandenheuvel.online>"]
license = "MIT"
repository = "https://github.com/vandenheuvel/rust-lp"
description = "A solver for linear programs"

edition = "2018"

[dependencies]
itertools = "0.10.0"
num = "0.3.1"

# TODO(PACKAGING): Make this an optional dependency.
daggy = "0.7.0"  # Currently only for debug asserts

clap = { version = "3.0.0-beta.2", optional = true }

[features]
burkardt = []
miplib = []
netlib = []
unicamp = []
cook = []

binaries = ["clap"]

[profile.release]
lto = true

[[bin]]
name = "rust-lp"
path = "src/bin/main.rs"
required-features = ["binaries"]
