[package]
name = "relp"
version = "0.0.4"
authors = ["Bram van den Heuvel <bram@vandenheuvel.online>"]
edition = "2018"
description = "Rust Exact Linear Programming"
repository = "https://github.com/vandenheuvel/relp"
license = "MIT"

keywords = ["linear", "exact", "precision", "ilp", "simplex"]
categories = ["algorithms", "science"]

[dependencies]
itertools = "0.10.0"
num = "0.4.0"

# TODO(PACKAGING): Make this an optional dependency.
daggy = "0.7.0"  # Currently only for debug asserts

clap = { version = "3.0.0-beta.2", optional = true }

[features]
burkardt = []
miplib = []
netlib = []
unicamp = []
cook = []

binaries = ["clap"]

[profile.release]
lto = true

[[bin]]
name = "relp"
path = "src/bin/main.rs"
required-features = ["binaries"]

