name: build

on: 
  [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  
jobs:
  check:
    name: Rust project
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run cargo test
        run: |
          cargo +nightly test

      - name: Run integration tests
        run: |
          cargo +nightly test --package relp --all-features --release --test mod

      - name: Generate code coverage
        run: |
          cargo +nightly tarpaulin --verbose --workspace --out xml

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v5

